name: Mirror Repo

on: [push, delete]

jobs:
  mirror_repo_to_foundation_foundation:
    name: Mirror Repo to TarsFoundation TarsFoundation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Mirro Repo
        if: !!secrets.TARS_GITHUB_MIRROR_KEY
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:tarsfoundation/TarsFoundation.git
          ssh_private_key: ${{ secrets.TARS_GITHUB_MIRROR_KEY }}
